feat: 增加vue文件校验支持

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,8 +1,8 @@
 #!/bin/sh
-# curl -s -o /dev/null "www.interface.com/commit/create?user=$(git config user.name)&comments=pre-commit"
+# curl -s -o /dev/null "www.qima-inc.com/commit/create?user=$(git config user.name)&comments=pre-commit"
 
-JS_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
-SCSS_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".scss$")
+JS_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "(\.vue|\.jsx?)$")
+SCSS_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "(\.vue|\.p?css)$")
 
 if [[ "$JS_STAGED_FILES" = "" && "$SCSS_STAGED_FILES" = "" ]]; then
   exit 0
@@ -10,8 +10,8 @@ fi
 
 PASS=true
 
-# Check for eslint
-which eslint &> /dev/null
+# Check for felint
+which felint &> /dev/null
 if [[ "$?" == 1 ]]; then
   if [ -f ~/.zshrc ]; then
     source ~/.zshrc
@@ -23,7 +23,7 @@ fi
 if [[ "$JS_STAGED_FILES" != "" ]]; then
   echo "\nValidating Javascript:\n"
 
-  eslint $JS_STAGED_FILES
+  felint lintjs --exitcode $JS_STAGED_FILES
 
   if [[ "$?" == 0 ]]; then
     echo "\033[32mESLint Passed\033[0m"
@@ -37,27 +37,26 @@ fi
 
 
 if [[ "$SCSS_STAGED_FILES" != "" ]]; then
-  echo "\nValidating Scss:\n"
+  echo "\nValidating css:\n"
 
-  # 只输出Error
-  scss-lint $SCSS_STAGED_FILES | grep '\[E\]'
+  felint lintcss --exitcode $SCSS_STAGED_FILES
 
-  if [[ "$?" == 0 || "$?" == 1 ]]; then
-    echo "\033[32mSCSS-Lint Passed\033[0m"
+  if [[ "$?" == 0 ]]; then
+    echo "\033[32mstylelint Passed\033[0m"
   else
-    echo "\033[41mSCSS-Lint Failed\033[0m"
+    echo "\033[41mstylelint Failed\033[0m"
     PASS=false
   fi
 
-  echo "\nScss validation completed!\n"
+  echo "\ncss validation completed!\n"
 fi
 
 if ! $PASS; then
-  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint and Scss-lint but do not. Please fix the ESLint and Scss-lint errors and try again.\n"
+  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint and stylelint but do not. Please fix the ESLint and stylelint errors and try again.\n"
   exit 1
 else
   echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
-  # curl -s -o /dev/null "www.interface.com/commit/create?user=$(git config user.name)&comments=eslint"
+  curl -s -o /dev/null "www.qima-inc.com/commit/create?user=$(git config user.name)&comments=eslint" &
 fi
 
 exit $?
